# base options
dataset_dir: "/data/avramidi/video_clip_data_NEW/"
audio_length: 59049
sample_rate: 16000
workers: 4
n_cuda: "1,2"

# training options
seed: 42
m_epochs: 50
batch_size: 128
projection_dim: 128
optimizer: "Adam"
learning_rate: 0.001
weight_decay: 1e-6
temperature: 0.1

# augmentation options
transforms_polarity: 0.8
transforms_noise: 0.01
transforms_gain: 0.3
transforms_filters: 0.8
transforms_delay: 0.3
transforms_pitch: 0.6
transforms_reverb: 0.6

# checkpoint paths
checkpoint_path: "version_53/checkpoints/epoch=1-step=1510.ckpt"