# dataset options
dataset: "MIRISE"
dataset_dir: "/data/shared_folder/toyota/toyota_no_video/"
streams: ["ECG"]
gtruth: "None"

# model options
in_channels: 1
base_filters: 16
kernel_size: 3
stride: 2
groups: 1
n_block: 8
n_classes: 256
projection_dim: 64
output_dim: 2

# training options:
batch_size: 64
m_epochs: 50
optimizer: "Adam"
learning_rate: 0.001
weight_decay: 1e-6
temperature: 0.1
val_freq: 1     # how often to validate (runs validation every val_freq epochs)
log_freq: 2     # how often to log (logs every log_freq steps)
workers: 4
n_cuda: "2"
bit_precision: 16
seed: 42
ckpt_path: null     # not used if set to null
ssl_ckpt_path: "ckpt/trans_epoch=99-step=97300.ckpt"

# logging options:
log_dir: "runs"
experiment_name: "cls_mirise"
experiment_version: null