# dataset options
dataset_dir: "/data/avramidi/tiles_ecg/"
contrastive: 0

# model options
in_channels: 1
base_filters: 64
kernel_size: 3
stride: 2
groups: 1
n_block: 10
n_classes: 256
projection_dim: 8   # this changes depending on SSL task [128, 8]

# training options:
batch_size: 256
m_epochs: 100
optimizer: "Adam"
learning_rate: 0.001
weight_decay: 1e-6
temperature: 0.1
val_freq: 1     # how often to validate (runs validation every val_freq epochs)
log_freq: 10    # how often to log (logs every log_freq steps)
workers: 4
n_cuda: "1"
bit_precision: 16
seed: 42
ckpt_path: null     # not used if set to null

# logging options:
log_dir: "runs"
experiment_name: "trans_trial"
experiment_version: null