# base options
audio_length: 59049
sample_rate: 16000
dataset: "mtg-jamendo-dataset"
dataset_dir: "/data/avramidi/mtg-jamendo-dataset"
workers: 4
n_cuda: "1,2,3"

# training options
seed: 42
batch_size: 128
projection_dim: 128
optimizer: "Adam"
learning_rate: 0.001
weight_decay: 1e-6
temperature: 0.1

checkpoint_path: "VCMR-audio_visual/version_1/checkpoints/epoch=4-step=1885.ckpt"
checkpoint_eval: "version_4/checkpoints/epoch=32-step=759.ckpt"